### ISSUE TITLE
Cannot download zip

### ISSUE THREAD

**Issue by renzo38** [exanimomeo/critical-hits-revisited#1]
Copy/paste module.json into foundry leads to an error, perhaps the zip file referenced in module.json should be renamed.
I do not know how to make a release, can you tell me howto ?

Thanks

**Comment by exanimomeo** [comment]
This is because the module,json is referencing the wrong location. I will correct this with release 1.20.

**Comment by exanimomeo** [comment]
Release 1.20 has come out, and I have confirmed it can be downloaded from the link. I will update the ReadMe to include the url to copy and paste.
